### PR TITLE
feat: add support for `-d`

### LINKED ISSUE #8: Option to ignore directories
Would it be possible to add a way to ignore certain files/directories (like the -I option in the unix `tree`)?

### PR DESCRIPTION
**Pull request by ByteBaker**
Closes #8 

- only list directories by using `-d` flag

### CODE REVIEW

**Comment by ByteBaker** [comment]
Hi @sighol, please review this and let me know how it is. I'll write code for `-I` in the next week perhaps.

**Comment by sighol** [comment]
It looks like this PR broke the tests.
The tests in this projects really needs some refactoring, because it is a bit annoying to run them right now.
You first need to build with release mode, and then run cargo test.
It looks like something around the `is_last` calculation is wrong.

This used to be the output of `cargo run -- tests`, 
```
├── compare
├── simple
│   └── yyy
│       ├── k
│       ├── s
│       │   ├── a
│       │   └── t
│       ├── test.txt
│       └── zz
│           └── a
│               └── b
│                   └── c
└── timer.py

7 directories, 6 files
```
And now it returns
```
tests
└── compare
├── simple
│   └── yyy
│       └── k
│       └── s
│           └── a
│           ├── t
│       ├── test.txt
│       ├── zz
│       │   └── a
│       │       └── b
│       │           └── c
├── timer.py

7 directories, 6 files
```

And thank you for making this PR! I am motivated to refactor the tests now, and maybe add some github actions.

**Comment by ByteBaker** [comment]
My bad. Yes, I didn't run the tests, at all! Lemme go back and see what's up with this.

And yes, they do need refactoring. In fact the whole project. Personally, I think we should open an issue to track the roadmap around the following tasks (not in the same order). Please feel free to add or remove some.

- [ ] Refactor the project structure, debloat `main.rs`.
- [ ] Add documentation to track features ported from `tree` and the ones for future.
- [ ] Add support for `-I` flag.
- [ ] Add more test cases and refactor existing ones.
- [ ] Benchmark the code and improve. Currently `tree-rs` seems to be slower than `tree`.
- [ ] Work on issue #14 

What do you think?

**Comment by sighol** [comment]
Since we talked about doing some refactorings, I pushed some changes that I think improved the structure somewhat.
https://github.com/sighol/tree-rs/pull/17

It unfortunately broke your PR, but that should hopefully be easy to resolve.

**Comment by sighol** [comment]
Found the error. This patch should fix it up. 
```patch
diff --git a/src/pathiterator.rs b/src/pathiterator.rs
index 40f1059..72bb7f4 100644
--- a/src/pathiterator.rs
+++ b/src/pathiterator.rs
@@ -102,16 +100,12 @@ impl FileIterator {
                 )
             });
 
-        for entry in entries {
-            let item = IteratorItem::new(&entry.path(), item.level + 1, false);
+        for (index, entry) in entries.iter().enumerate() {
+            let item = IteratorItem::new(&entry.path(), item.level + 1, index == 0);
             if self.is_included(&item.file_name, item.is_dir()) {
                 self.queue.push_back(item);
             }
         }
-
-        if let Some(item) = self.queue.back_mut() {
-            item.is_last = true;
-        }
     }
 }
 ```

The `queue` is kept for multiple iterations, so it can contain folders on different levels. Setting `is_last` must be set based on the entries, not on the queue.

**Comment by ByteBaker** [comment]
Hi @sighol, got a little occupied during the weekend and couldn't work on this one.

But hey, thanks a ton for the carry with the patch. I've made the change and pushed it here. See if it looks good to you.
I'm also gonna create the tracker issue as discussed earlier.

**Pull request merged**
